### ISSUE TITLE
What tools do you find indispensable in your typical day-to-day?

### ISSUE THREAD

**Issue by cmilhench** [paulja/ama#1]

**Comment by paulja** [comment]
A typical day for could be developing node services, iOS apps, writing an article or documentation, or going some graphic / UX design work.

So I'll break the answer down into some broad categories—there are my indispensable tools, not just often used, but truly things I would miss if they were not to hand:

### Development 

My goto text editor is [TextMate](http://macromates.com), for just about everything, and [Xcode](https://developer.apple.com/xcode/) for everything else. When I need to work on files remotely I typically use [rmate](https://github.com/textmate/rmate) over SSH ([here's a post on how to set that up](https://medium.com/@pj_/remote-mate-81614224bb85)).

I do a lot of service/web and API development, and for that I *need* [Charles](http://www.charlesproxy.com) and [Paw](https://luckymarmot.com/paw)—both are amazing tools, absolutely indispensable.

For source control I use [Git](https://git-scm.com), mainly at the command-line with a few custom aliases to make life a little sweeter, but I also like a nice visualisation tool, so I use and recommend [GitUp](http://gitup.co), but I'm not sure it's indispensable... maybe in time it will become so.

### Writing

[Typed](http://realmacsoftware.com/typed/)! I love the writing experience with Typed and use it for writing just about everything, from emails to this issue reply right now! 

### Design

My daily design toolbox breaks down to just two [tools—Pixelmator](http://www.pixelmator.com) and [Sip](http://theolabrothers.com), both are essential for any of my design work.

### Others

I have a few other indispensable  tools that I use every day: [Dropbox](https://www.dropbox.com), [Jumpcut](http://jumpcut.sourceforge.net), and For managing my short and long term work queue [Clear](http://realmacsoftware.com/clear/) is the tool for me.
